name: Deploy Bevy Game to GitHub Pages

on:
  push:
    branches:
      - master  # TODO - deploy from release after it goes through approval process

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
        override: true

    - name: Build wasm package
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --target wasm32-unknown-unknown

    - name: Run wasm-bindgen
      run: wasm-bindgen --no-typescript --target web --out-dir ./out/ --out-name "nodal" ./target/wasm32-unknown-unknown/release/nodalbevy.wasm

    - name: Copy assets
      run: cp -r ./assets ./out/assets

    - name: Copy index.html
      run: cp ./index.html ./out/index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out
